meteo/accounts/urls.py
from django.urls import path

from .views import LogInView, SignUpView, LogOutView

app_name = "accounts"

urlpatterns = [
    path("log-in/", LogInView.as_view(), name="log_in"),
    path("log-out/", LogOutView.as_view(), name="log_out"),
    path("sign-up/", SignUpView.as_view(), name="sign_up"),
]

meteo/app/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main.views import IndexPageView, RetirementPageView


urlpatterns = [
    path("", IndexPageView.as_view(), name="index"),
    path("me/", RetirementPageView.as_view(), name="me"),
    path("accounts/", include("accounts.urls")),
] 
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

meteo/accounts/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

meteo/accounts/forms.py
from django import forms
from django.forms import ValidationError
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from accounts.models import CustomUser


class UserCacheMixin:
    user_cache = None


class SignIn(UserCacheMixin, forms.Form):
    password = forms.CharField(
        label=_("Password"), strip=False, widget=forms.PasswordInput
    )


class SignInViaUsernameForm(SignIn):
    username = forms.CharField(label=_("Username"))

    @property
    def field_order(self):
        return ["username", "password"]

    def clean_username(self):
        username = self.cleaned_data["username"]

        user = CustomUser.objects.filter(username=username).first()
        if not user:
            raise ValidationError(_("You entered an invalid username."))

        if not user.is_active:
            raise ValidationError(_("This account is not active."))

        self.user_cache = user

        return username


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = settings.SIGN_UP_FIELDS

meteo/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import View, FormView
from django.conf import settings


from .forms import SignInViaUsernameForm, SignUpForm


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = "accounts/log_in.html"

    @staticmethod
    def get_form_class(**kwargs):
        return SignInViaUsernameForm

    def form_valid(self, form):
        username, password = form.cleaned_data.get("username"), form.cleaned_data.get(
            "password"
        )
        new_user = authenticate(username=username, password=password)
        if new_user:
            login(self.request, new_user)
        return redirect("/")

    def post_login(sender, user, request, response, **kwargs):
        response.set_cookie("uid", user.uuid)
        return response


class SignUpView(GuestOnlyView, FormView):
    template_name = "accounts/sign_up.html"
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)
        user.username = form.cleaned_data["username"]
        user.is_active = True
        user.save()
        raw_password = form.cleaned_data["password1"]
        user = authenticate(username=user.username, password=raw_password)
        login(request, user)
        messages.success(request, _("You are successfully signed up!"))
        return redirect("index")


class LogOutView(LoginRequiredMixin, BaseLogoutView):
    template_name = "accounts/log_out.html"

meteo/main/views.py
from django.views.generic import TemplateView, View
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, JsonResponse

import requests

from app.settings import FLAG


@method_decorator(login_required, name="dispatch")
class IndexPageView(TemplateView):
    template_name = "main/index.html"

    def post(self, request):
        value = request.POST.get("choice")
        if not value:
            value = "0"

        uuid = request.COOKIES.get("uuid")
        r = requests.get(
            f"http://chatgpt.local:8000/api/v1/retirement/set/{uuid}",
            params={"retirement": 64, "choice": value},
        )
        if not r.ok:
            headers = {e.lower(): r.request.headers[e] for e in r.request.headers}
            return JsonResponse(
                {
                    "error": True,
                    "response": r.text,
                    "url": r.request.url,
                    "headers": headers,
                },
                status=400,
            )
        return redirect("/me")


@method_decorator(login_required, name="dispatch")
class RetirementPageView(View):
    template_name = "main/me.html"

    def get(self, request, *args, **kwargs):
        uuid = request.COOKIES.get("uuid")
        r = requests.get(
            f"http://chatgpt.local:8000/api/v1/retirement/get/{uuid}",
        )
        retirement = None

        if not r.ok:
            headers = {e.lower(): r.request.headers[e] for e in r.request.headers}
            return JsonResponse(
                {
                    "error": True,
                    "response": r.text,
                    "url": r.request.url,
                    "headers": headers,
                },
                status=400,
            )
        retirement = r.json()["retirement"]
        return render(
            request, self.template_name, {"retirement": retirement, "flag": FLAG}
        )

meteo/accounts/templates/accounts/log_in.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Log in' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Log in' %}</button>

    </form>

{% endblock %}

meteo/accounts/templates/accounts/log_out.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

meteo/accounts/templates/accounts/sign_up.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Create an account' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-success">{% trans 'Create' %}</button>

    </form>

{% endblock %}

meteo/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A challenge for the 2023 edition of 'le Hack'">
    <meta name="author" content="Aethlios (https://aeth.cc)">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>Météo de ma retraite</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="{% url 'index' %}">Home</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">Signup</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid mt-3">
    {% bootstrap_messages %}
    {% block content %}
        No content.
    {% endblock %}
</div>
</body>
</html>

meteo/content/templates/main/index.html
{% extends 'layouts/default/page.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<div
  class="max-w-1200 m-auto p-[7vw] items-center pb-10 pt-0 flex flex-col lg:pr-0 lg:pl-0 lg:grid lg:grid-cols-12 lg:gap-x-9 gap-y-5 auto-rows-min"
>
  <h1
    class="text-4xl leading-tight text-center text-scn-blue-800 lg:mb-3 lg:col-span-6 lg:col-start-4"
  >
    <span class="font-bold">My retirement pension</span>
  </h1>
  <div class="text-center">
    <p>
    The government gives you the keys to decipher the impact of the reform on your retirement pension. 
    </p>
    <p>
        The amended Social Security Financing Act for 2023, Act of April 14, 2023, has been published in the Official Journal. It will come into force on September 1, 2023.
    </p>
    <p>
        In one click, artificial intelligence via blockchain and NFT will determine in real time and definitively until when you will work before receiving your retirement pension.
    </p>
    <p style="color: grey">
      For (real) information on the main measures affecting the French people, see <a href="https://la-reforme-des-retraites-et-moi.fr" class="">this (real) page.</a> and <a href="https://www.mediapart.fr/journal/economie-et-social/200323/reforme-des-retraites-les-points-clefs-de-la-version-finale">this other (real) resource</a>.
    </p>
  </div>
  <div
    class="bg-white rounded-md max-w-[582px] pb-7 lg:col-span-6 lg:col-start-4 min-h-min layout-form"
    data-v-8218032c=""
  >
    <div class="text-center text-xs text-scn-blue-800 pt-5">
      <span class="font-bold">STEP 1/1</span> —
      <span class="uppercase">Your situation</span>
    </div>
    <div class="text-center">
      <h2>
        Have you been wise in recent years?
      </h2>
      <form method="POST" novalidate="" class="flex flex-col gap-3">
        {% csrf_token %}
        <div>
            <label>
                <input type="radio" name="choice" id="choice1" value="0" />
                No way
            </label>
        </div>
        <div>
            <label>
                <input type="radio" name="choice" id="choice2" value="1" />
                Yes, don't you think ?
            </label>
        </div>
        <div>
            <label>
                <input type="radio" name="choice" id="choice3" value="2" />
                Yes, very much so
            </label>
        </div>
        <button class="btn-primary m-auto mt-4">Next step</button>
      </form>
    </div>
  </div>
</div>
{% else %}
<b>Please login or register</b>
{% endif %}
{% endblock %}

meteo/content/templates/main/me.html
{% extends 'layouts/default/page.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<div
  class="max-w-1200 m-auto p-[7vw] items-center pb-10 pt-0 flex flex-col lg:pr-0 lg:pl-0 lg:grid lg:grid-cols-12 lg:gap-x-9 gap-y-5 auto-rows-min"
>
  <h1
    class="text-4xl leading-tight text-center text-scn-blue-800 lg:mb-3 lg:col-span-6 lg:col-start-4"
  >
    <span class="font-bold">My retirement pension</span>
  </h1>
  <div class="text-center">
    <p>
      After multiple and thorough researches thanks to a totally impartial and objective artificial intelligence, the decision can not be contested, here is the age of departure to the retirement:
    </p>
    <h2>
      {% if retirement < 64 %} {{ flag }} {% elif retirement >= 64 %} {{ retirement }} {% else %} <a href="/">See this page</a>{% endif %}
    </h2>
    <p>
      It's the AI that says it, not us, and then you have to be able to pay back the state's debt anyway.
    </p>
  </div>
</div>
{% else %}
<b>Please login or register</b>
{% endif %}
{% endblock %}